version: '3'
services:
  stats_backend:
    build: .
    container_name: stats_backend
    restart: always
    ports:
      - "127.0.0.1:7009:80"
    environment:
      - VIRTUAL_HOST=health-nlp.stats.jdonado.com
      - LETSENCRYPT_EMAIL=jdonado@jdonado.com
      - LETSENCRYPT_HOST=health-nlp.stats.jdonado.com
    networks:
      - health-nlp-network
      - jdonado-nw
    expose:
      - 8888

networks:
  health-nlp-network:
    external:
      name: health-nlp-network
  jdonado-nw:
    external:
      name: jdonado-nw

